### ISSUE TITLE
Concern about backward for IndependentDiscreteDiffusion

### ISSUE THREAD

**Issue by murrellb** [MurrellGroup/Diffusions.jl#40]
Just noting this concern - will investigate more later. The issue is that, as t -> inf, it should return a vec of ones. This might not make a difference for what we're doing here, but it seems worth investigating.

**Comment by bicycle1885** [comment]
I'm not completely sure what you mean by "it should return a vec of ones". I think it does not converge to a vector of ones, if I understand it correctly.

So, we have a substitution model $P(x_t = j | x_0 = i) = \exp(rQt)$, where $r$ is a rate scaling parameter and $Q$ is a rate matrix. If we consider an IndependentDiscreteDiffusion model with equilibrium $\pi$, we will define $Q$ as $Q_{ij} = \pi_j$ for $i \ne j$ and its diagonal elements are defined such that the sum of each row equals zero. In this particular case, we can calculate the transition probability as $P(x_t = j | x_0 = i) = \pi_j (1 - e) + e \delta_{ij}$, where $e = \exp(-rt)$. As $t$ goes to infinity, we'll get $P(x_t = j | x_0 = i) = \pi_j$ because $e$ goes to zero for any $r > 0$. That means, a backward vector $v$, which is defined as $v_i = P(x_t = j | x_0 = i)$ for given $x_t = j$, also converges to $\pi_j$, which is consistent with the current behavior.

Let me know if I misunderstand something.

**Comment by murrellb** [comment]
Sorry - this was for a placeholder for a specific case which I didn't elaborate on further. I didn't mean to assign you to it!

I don't think it is correct that a "backward" run should converge to $\pi$, in general. Take the case where $\pi$ is $[1,0,0,0]$. As $t => \inf$, we have 100% switched into state 1 no matter which state we started in, so if $x_t$ was $[1,0,0,0]$, then $v = [1,1,1,1]$. If $x_t$ was, say, $[0,1,0,0]$, then $v = [0,0,0,0]$. In general, it should converge to $\pi.x_t$, I think?

But I think the current code does this (confirm pls?), so I'm not sure what my concern was!
